import '../styles/style.scss'
import './components/home/header'
import './components/home/recomen'
import './components/search/result'
import './components/search/header'
import './components/detail/content'
import './components/common/card'
import './components/common/nav'
